### ISSUE TITLE
Doesn't work inside a SplitWindow

### ISSUE THREAD

**Issue by sindresorhus** [k0sukey/TiISRefreshControl#2]
When I try to drag the list down to see the refreshcontrol it just releases the list immediately which makes it impossible to drag it down enough to refresh.

Test case:

``` js
function createWin() {
    var win = Ti.UI.createWindow();

    var list = Ti.UI.createListView({
        refreshControlEnabled: true
    });

    list.addEventListener('refreshstart', function () {
        setTimeout(function () {
            list.refreshFinish();
        }, 1000);
    });

    win.add(list);

    return win;
}

var win = Ti.UI.iPad.createSplitWindow({
    detailView: createWin(),
    masterView: Ti.UI.createWindow()
});

win.open();
```

Using https://github.com/k0sukey/TiISRefreshControl/commit/d22dbde1e536841e05cf3b9edd1db8b38442f421

**Comment by k0sukey** [comment]
I fixed. I think cause that's the same as #3.

**Comment by sindresorhus** [comment]
No, it's still an issue. You have to be in landscape on the iPad simulator to see it. Try dragging the listview down.

**Comment by k0sukey** [comment]
OK, I was confirmed in iPad on landscape. Give me time.

**Comment by k0sukey** [comment]
I think the behavior of the ListView and TableView when SplitWindow is rotated is wrong to. Of course, without this module. I think it can be avoided in this code.

```
var detail = Ti.UI.createWindow();
var list = Ti.UI.createListView();
detail.add(list);

var split = Ti.UI.iPad.createSplitWindow({
  masterView: Ti.UI.createWindow(),
  detailView: detail
});
split.open();

Ti.Gesture.addEventListener('orientationchange', function(){
  list.applyProperties({
    height: Ti.Platform.displayCaps.platformHeight
  });
});
```
